### ISSUE TITLE
Apply pr doesn't apply but marks as success

### ISSUE THREAD

**Issue by mroig** [gisce/apply_pr#38]
It downloaded the patches, uploaded them and started applying but it stayed at 0% and didn't actually apply anything.

Despite that, it didn't give any kind of error or warning and it marked the deploy as a success.

This was done while applying the PR https://github.com/gisce/erp/pull/4014.

The server was on branch rolling and did not have any of the files that are changed on the PR modified in any way. It could not be applied directly with `git am` but it failed at the commit 0051, not the first one.

**Comment by mroig** [comment]
The same happened after that, while trying to deploy gisce/erp#3412.

**Comment by ecarreras** [comment]
Try to define user configuration for git to fabric user:

```
git config --global user.name "Fabric"
git config --global user.email "hello@devnull"
```
