### ISSUE TITLE
Using --force-hostname option for apply_pr doesn't work properly

### ISSUE THREAD

**Issue by gdalmau** [gisce/apply_pr#59]
# Expectation

Using `--force-hostname` should mark the Pull Request as deployed on github with the name passed as parameter.

# Error

The parameter `--force-hostname` is passed to the argument `skip_upload` and it is not exporting patches neither uploading it to the server.

**Comment by jaumef** [comment]
Closed due to #60 closing this issue.

The "Fix" tag was added after merging and so the issue wasn't merged
